// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecwmyjrjoughugrzdndf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjd215anJqb3VnaHVncnpkbmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjQ0OTQsImV4cCI6MjA2NDUwMDQ5NH0.3sr_6mW3yASLfth2xLQQzAGSyHolADPBIvszDtSIP3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);